[package]
name = "xbox-sg"
version = "0.1.0"
authors = ["Kern <kern.walster@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.24"
ring = "0.11.0"
untrusted = "0.5.0"
rust-crypto = "0.2.36"
nom = "3.2.0"
protocol = "0.3.1"
quick-error = "1.2.1"
bit_field = "0.7.0"
